name: Java Maven CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker image
      run: docker tag your-image-name:latest ghcr.io/kassomeone/docker-hello-world-spring-boot/:latest

    - name: Push Docker image
      run: docker push ghcr.io/kassomeone/docker-hello-world-spring-boot/:latest
